FROM amazoncorretto:17-alpine-jdk

WORKDIR /app

COPY /build/libs/ticket-concurrency-with-synchronized-0.0.1-SNAPSHOT.jar app.jar

ENV TZ=Asia/Seoul

ENTRYPOINT ["java", "-Dspring.profiles.active=server2", "-jar", "app.jar"]
